server:
  port: 9002

spring:
  application:
    name: JUCMysql

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JUC?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456789
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath:mapper/*.xml
